steps:
# Step 1: Build the Docker image
# This step builds a Docker image using the Dockerfile in the current directory.
# The image is tagged with gcr.io/<PROJECT_ID>/fe-rekapkeu and the commit SHA.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fe-rekapkeu:$COMMIT_SHA', '.']
  id: 'Build Docker Image'

# Step 2: Push the Docker image to Google Container Registry
# This step pushes the newly built Docker image to Google Container Registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/fe-rekapkeu:$COMMIT_SHA']
  id: 'Push Docker Image'

# Step 3 (Optional): Deploy to Google Cloud Run
# Uncomment and modify this step if you want to automatically deploy your frontend
# to a Cloud Run service after a successful build.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'fe-rekapkeu' # Name of your Cloud Run service (e.g., fe-rekapkeu-service)
  - '--image'
  - 'gcr.io/$PROJECT_ID/fe-rekapkeu:$COMMIT_SHA'
  - '--region'
  - 'asia-southeast2' # IMPORTANT: Choose the Google Cloud region closest to your users (e.g., us-central1, asia-southeast2)
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' # Allows public access. Use '--no-allow-unauthenticated' for private access.
  id: 'Deploy to Cloud Run'

# Define the images that will be built and pushed as part of this build process.
images:
- 'gcr.io/$PROJECT_ID/fe-rekapkeu:$COMMIT_SHA' # Removed the extra word "perbaiki"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1600s" # Timeout untuk seluruh build